[pytest]
testpaths = tests
# --allure tells pytest where to save the raw JSON results
addopts = -v -s -n 2 --alluredir=allure-results --clean-alluredir

markers =
    smoke: mark a test as a smoke test.
    regression: mark a test as a regression test.
    integration: mark a test as an integration test.
    unit: mark a test as a unit test.
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S

